spring:
  application:
    name: CustomerInfo
  profiles:
    active: dev

---

server:
  port: 8080
  
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:customer
    username: root
    password: customer@123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true